# Generated by Django 3.1.1 on 2020-09-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='luxioncategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='luxionsubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
                ('official_name', models.CharField(max_length=200)),
                ('type_name', models.CharField(max_length=200)),
                ('buy_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.luxioncategory')),
            ],
        ),
    ]
