# Generated by Django 3.1.1 on 2020-09-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=200)),
                ('type_name', models.CharField(max_length=200)),
                ('buy_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='luxioncategory',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='luxionsubcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='subCat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.subcategory'),
        ),
    ]
