# Generated by Django 3.1.1 on 2020-09-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200914_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cat_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.category'),
            preserve_default=False,
        ),
    ]
