# Generated by Django 3.1.1 on 2020-09-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_products_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
